[params]
ShowReadingTime = true
archiveByDefault = true # use archive layout for home

[params.fuseOpts] # need this for search
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
  name = "Misc"
  weight = 3
  url = "/misc"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 2
[[menu.main]]
  name = "🎹"
  url = "/music"
  weight = 4
[[menu.main]]
  name = "🔖"
  weight = 5
  url = "/bookmarks"
#[[menu.main]] # for PaperMod
#  name = "🔍"
#  weight = 6
#  url = "/search"

[params.homeInfoParams]
#Title = "KONOMAMA's BLOG"
Content = """
- 本blog部分外链及内嵌内容🇨🇳需vpn (有很多youtube, google系服务, wiki链接)
- 有任何需要欢迎留言(邮箱非必填，除非订阅对话)
- 若订阅对话请检查垃圾邮件: `mail.konomama.dev@gmail.com`
- 请谨慎分享本blog文章到微信，腾讯会自动用爬虫爬取被分享的文章，可能是要检测是否有“非法内容”
"""

[[params.socialIcons]]
name = "rss"
url = "https://blog.konomama.dev/index.xml"
#[[params.socialIcons]]
#name = "bilibili"
#url = "https://space.bilibili.com/1497254925/"
[[params.socialIcons]]
name = "lastfm"
url = "https://www.last.fm/user/iloveWinnie"
[[params.socialIcons]]
name = "steam"
url = "https://steamcommunity.com/profiles/76561198844206094"
[[params.socialIcons]]
name = "letterboxd"
url = "https://letterboxd.com/konomama/likes/films/"

[params.assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false
style = "catppuccin-latte" #"solarized-light" "github"